# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'

EngineSample::Application.load_tasks

namespace :engine do
  task :create, :engine do |cmd, args|
    puts "Creating symbolic links..."
    system "mkdir #{Rails.root.to_s}/public/#{args[:engine]}"
    system "ln -s #{Rails.root.to_s}/vendor/plugins/#{args[:engine]}/public/* #{Rails.root.to_s}/public/#{args[:engine]}"
    system "ln -s #{Rails.root.to_s}/vendor/plugins/#{args[:engine]}/db/migrate/* #{Rails.root.to_s}/db/migrate/"
    puts "Done!"
  end
end
